name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Decode signing key
        run: |
          echo "${{ secrets.SIGNING_SECRET_KEY_RING }}" | base64 -d > ${{ runner.temp }}/secret.gpg

      - name: Publish to Maven Central
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signing_keyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signing_password: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signing_secretKeyRingFile: ${{ runner.temp }}/secret.gpg
        run: |
          ./gradlew \
            :perseus-core:publishAndReleaseToMavenCentral \
            :perseus-interop:publishAndReleaseToMavenCentral
